// Mocks generated by Mockito 5.4.6 from annotations
// in parcel_am/test/features/notifications/presentation/screens/notifications_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:flutter_bloc/flutter_bloc.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:parcel_am/core/bloc/base/base_state.dart' as _i4;
import 'package:parcel_am/features/notifications/domain/usecases/notification_usecase.dart'
    as _i2;
import 'package:parcel_am/features/notifications/presentation/bloc/notification_bloc.dart'
    as _i3;
import 'package:parcel_am/features/notifications/presentation/bloc/notification_event.dart'
    as _i8;
import 'package:parcel_am/features/notifications/presentation/bloc/notification_state.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNotificationUseCase_0 extends _i1.SmartFake
    implements _i2.NotificationUseCase {
  _FakeNotificationUseCase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NotificationBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationBloc extends _i1.Mock implements _i3.NotificationBloc {
  MockNotificationBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NotificationUseCase get notificationUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#notificationUseCase),
            returnValue: _FakeNotificationUseCase_0(
              this,
              Invocation.getter(#notificationUseCase),
            ),
          )
          as _i2.NotificationUseCase);

  @override
  _i4.BaseState<_i5.NotificationData> get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i6.dummyValue<_i4.BaseState<_i5.NotificationData>>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i4.BaseState<_i5.NotificationData>);

  @override
  _i7.Stream<_i4.BaseState<_i5.NotificationData>> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue:
                _i7.Stream<_i4.BaseState<_i5.NotificationData>>.empty(),
          )
          as _i7.Stream<_i4.BaseState<_i5.NotificationData>>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void add(_i8.NotificationEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i8.NotificationEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i4.BaseState<_i5.NotificationData>? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i8.NotificationEvent>(
    _i9.EventHandler<E, _i4.BaseState<_i5.NotificationData>>? handler, {
    _i9.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i9.Transition<_i8.NotificationEvent, _i4.BaseState<_i5.NotificationData>>?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i9.Change<_i4.BaseState<_i5.NotificationData>>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
