// Mocks generated by Mockito 5.4.6 from annotations
// in parcel_am/test/features/parcel_am_core/presentation/bloc/parcel_bloc_realtime_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:parcel_am/core/errors/failures.dart' as _i6;
import 'package:parcel_am/features/parcel_am_core/data/repositories/parcel_repository_impl.dart'
    as _i2;
import 'package:parcel_am/features/parcel_am_core/domain/entities/parcel_entity.dart'
    as _i7;
import 'package:parcel_am/features/parcel_am_core/domain/usecases/parcel_usecase.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeParcelRepositoryImpl_0 extends _i1.SmartFake
    implements _i2.ParcelRepositoryImpl {
  _FakeParcelRepositoryImpl_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ParcelUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockParcelUseCase extends _i1.Mock implements _i4.ParcelUseCase {
  MockParcelUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ParcelRepositoryImpl get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeParcelRepositoryImpl_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ParcelRepositoryImpl);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.ParcelEntity>> createParcel(
    _i7.ParcelEntity? parcel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createParcel, [parcel]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i7.ParcelEntity>>.value(
                  _FakeEither_1<_i6.Failure, _i7.ParcelEntity>(
                    this,
                    Invocation.method(#createParcel, [parcel]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.ParcelEntity>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.ParcelEntity>> updateParcelStatus(
    String? parcelId,
    _i7.ParcelStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateParcelStatus, [parcelId, status]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i7.ParcelEntity>>.value(
                  _FakeEither_1<_i6.Failure, _i7.ParcelEntity>(
                    this,
                    Invocation.method(#updateParcelStatus, [parcelId, status]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.ParcelEntity>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.ParcelEntity>> getParcel(
    String? parcelId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getParcel, [parcelId]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i7.ParcelEntity>>.value(
                  _FakeEither_1<_i6.Failure, _i7.ParcelEntity>(
                    this,
                    Invocation.method(#getParcel, [parcelId]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.ParcelEntity>>);

  @override
  _i5.Stream<_i3.Either<_i6.Failure, _i7.ParcelEntity>> watchParcelStatus(
    String? parcelId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchParcelStatus, [parcelId]),
            returnValue:
                _i5.Stream<_i3.Either<_i6.Failure, _i7.ParcelEntity>>.empty(),
          )
          as _i5.Stream<_i3.Either<_i6.Failure, _i7.ParcelEntity>>);

  @override
  _i5.Stream<_i3.Either<_i6.Failure, List<_i7.ParcelEntity>>> watchUserParcels(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchUserParcels, [userId]),
            returnValue:
                _i5.Stream<
                  _i3.Either<_i6.Failure, List<_i7.ParcelEntity>>
                >.empty(),
          )
          as _i5.Stream<_i3.Either<_i6.Failure, List<_i7.ParcelEntity>>>);

  @override
  _i5.Stream<_i3.Either<_i6.Failure, List<_i7.ParcelEntity>>>
  watchUserAcceptedParcels(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchUserAcceptedParcels, [userId]),
            returnValue:
                _i5.Stream<
                  _i3.Either<_i6.Failure, List<_i7.ParcelEntity>>
                >.empty(),
          )
          as _i5.Stream<_i3.Either<_i6.Failure, List<_i7.ParcelEntity>>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.ParcelEntity>>> getUserParcels(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserParcels, [userId]),
            returnValue:
                _i5.Future<
                  _i3.Either<_i6.Failure, List<_i7.ParcelEntity>>
                >.value(
                  _FakeEither_1<_i6.Failure, List<_i7.ParcelEntity>>(
                    this,
                    Invocation.method(#getUserParcels, [userId]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, List<_i7.ParcelEntity>>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.ParcelEntity>>>
  getAvailableParcels() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableParcels, []),
            returnValue:
                _i5.Future<
                  _i3.Either<_i6.Failure, List<_i7.ParcelEntity>>
                >.value(
                  _FakeEither_1<_i6.Failure, List<_i7.ParcelEntity>>(
                    this,
                    Invocation.method(#getAvailableParcels, []),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, List<_i7.ParcelEntity>>>);

  @override
  _i5.Stream<_i3.Either<_i6.Failure, List<_i7.ParcelEntity>>>
  watchAvailableParcels() =>
      (super.noSuchMethod(
            Invocation.method(#watchAvailableParcels, []),
            returnValue:
                _i5.Stream<
                  _i3.Either<_i6.Failure, List<_i7.ParcelEntity>>
                >.empty(),
          )
          as _i5.Stream<_i3.Either<_i6.Failure, List<_i7.ParcelEntity>>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.ParcelEntity>> assignTraveler(
    String? parcelId,
    String? travelerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#assignTraveler, [parcelId, travelerId]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i7.ParcelEntity>>.value(
                  _FakeEither_1<_i6.Failure, _i7.ParcelEntity>(
                    this,
                    Invocation.method(#assignTraveler, [parcelId, travelerId]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.ParcelEntity>>);
}
