// Mocks generated by Mockito 5.4.6 from annotations
// in parcel_am/test/features/travellink/presentation/bloc/wallet/wallet_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:parcel_am/core/errors/failures.dart' as _i6;
import 'package:parcel_am/features/travellink/domain/entities/transaction_entity.dart'
    as _i8;
import 'package:parcel_am/features/travellink/domain/entities/wallet_entity.dart'
    as _i7;
import 'package:parcel_am/features/travellink/domain/repositories/wallet_repository.dart'
    as _i2;
import 'package:parcel_am/features/travellink/domain/usecases/wallet_usecase.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWalletRepository_0 extends _i1.SmartFake
    implements _i2.WalletRepository {
  _FakeWalletRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WalletUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalletUseCase extends _i1.Mock implements _i4.WalletUseCase {
  MockWalletUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WalletRepository get walletRepo =>
      (super.noSuchMethod(
            Invocation.getter(#walletRepo),
            returnValue: _FakeWalletRepository_0(
              this,
              Invocation.getter(#walletRepo),
            ),
          )
          as _i2.WalletRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.WalletEntity>> getWallet(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWallet, [userId]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i7.WalletEntity>>.value(
                  _FakeEither_1<_i6.Failure, _i7.WalletEntity>(
                    this,
                    Invocation.method(#getWallet, [userId]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.WalletEntity>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.WalletEntity>> updateBalance(
    String? walletId,
    double? amount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBalance, [walletId, amount]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i7.WalletEntity>>.value(
                  _FakeEither_1<_i6.Failure, _i7.WalletEntity>(
                    this,
                    Invocation.method(#updateBalance, [walletId, amount]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.WalletEntity>>);

  @override
  _i5.Stream<_i3.Either<_i6.Failure, _i7.WalletEntity>> watchBalance(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchBalance, [userId]),
            returnValue:
                _i5.Stream<_i3.Either<_i6.Failure, _i7.WalletEntity>>.empty(),
          )
          as _i5.Stream<_i3.Either<_i6.Failure, _i7.WalletEntity>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.WalletEntity>> holdBalance(
    String? walletId,
    double? amount,
    String? referenceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#holdBalance, [walletId, amount, referenceId]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i7.WalletEntity>>.value(
                  _FakeEither_1<_i6.Failure, _i7.WalletEntity>(
                    this,
                    Invocation.method(#holdBalance, [
                      walletId,
                      amount,
                      referenceId,
                    ]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.WalletEntity>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.WalletEntity>> releaseBalance(
    String? walletId,
    double? amount,
    String? referenceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#releaseBalance, [walletId, amount, referenceId]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i7.WalletEntity>>.value(
                  _FakeEither_1<_i6.Failure, _i7.WalletEntity>(
                    this,
                    Invocation.method(#releaseBalance, [
                      walletId,
                      amount,
                      referenceId,
                    ]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.WalletEntity>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i8.TransactionEntity>> recordTransaction(
    String? walletId,
    double? amount,
    _i8.TransactionType? type,
    String? description,
    String? referenceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#recordTransaction, [
              walletId,
              amount,
              type,
              description,
              referenceId,
            ]),
            returnValue:
                _i5.Future<
                  _i3.Either<_i6.Failure, _i8.TransactionEntity>
                >.value(
                  _FakeEither_1<_i6.Failure, _i8.TransactionEntity>(
                    this,
                    Invocation.method(#recordTransaction, [
                      walletId,
                      amount,
                      type,
                      description,
                      referenceId,
                    ]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i8.TransactionEntity>>);
}
