// Mocks generated by Mockito 5.4.6 from annotations
// in parcel_am/test/core/bloc_manager/bloc_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_bloc/flutter_bloc.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:parcel_am/core/bloc_manager/bloc_lifecycle_observer.dart'
    as _i7;
import 'package:parcel_am/core/bloc_manager/bloc_manager_config.dart' as _i6;
import 'package:parcel_am/core/bloc_manager/plugins/bloc_manager_plugin.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BlocManagerPlugin].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlocManagerPlugin extends _i1.Mock implements _i2.BlocManagerPlugin {
  MockBlocManagerPlugin() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i3.dummyValue<String>(this, Invocation.getter(#name)),
          )
          as String);

  @override
  String get version =>
      (super.noSuchMethod(
            Invocation.getter(#version),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#version),
            ),
          )
          as String);

  @override
  _i4.Future<void> onBlocCreated(
    _i5.BlocBase<dynamic>? bloc,
    _i6.BlocManagerConfig? config,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#onBlocCreated, [bloc, config]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> onBlocDisposed(_i5.BlocBase<dynamic>? bloc) =>
      (super.noSuchMethod(
            Invocation.method(#onBlocDisposed, [bloc]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> onStateChange(
    _i5.BlocBase<dynamic>? bloc,
    Object? previousState,
    Object? newState,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#onStateChange, [bloc, previousState, newState]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> onError(
    _i5.BlocBase<dynamic>? bloc,
    Object? error,
    StackTrace? stackTrace,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#onError, [bloc, error, stackTrace]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [BlocLifecycleObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlocLifecycleObserver extends _i1.Mock
    implements _i7.BlocLifecycleObserver {
  MockBlocLifecycleObserver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void onBlocCreated(_i5.BlocBase<dynamic>? bloc) => super.noSuchMethod(
    Invocation.method(#onBlocCreated, [bloc]),
    returnValueForMissingStub: null,
  );

  @override
  void onBlocDisposed(_i5.BlocBase<dynamic>? bloc) => super.noSuchMethod(
    Invocation.method(#onBlocDisposed, [bloc]),
    returnValueForMissingStub: null,
  );

  @override
  void onBlocError(
    _i5.BlocBase<dynamic>? bloc,
    Object? error,
    StackTrace? stackTrace,
  ) => super.noSuchMethod(
    Invocation.method(#onBlocError, [bloc, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onBlocStateChange(
    _i5.BlocBase<dynamic>? bloc,
    Object? currentState,
    Object? nextState,
  ) => super.noSuchMethod(
    Invocation.method(#onBlocStateChange, [bloc, currentState, nextState]),
    returnValueForMissingStub: null,
  );
}
