// Mocks generated by Mockito 5.4.6 from annotations
// in parcel_am/test/features/chat/chat_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:parcel_am/core/errors/failures.dart' as _i6;
import 'package:parcel_am/features/chat/data/repositories/chat_repository_impl.dart'
    as _i2;
import 'package:parcel_am/features/chat/domain/entities/chat.dart' as _i9;
import 'package:parcel_am/features/chat/domain/entities/message.dart' as _i7;
import 'package:parcel_am/features/chat/domain/entities/message_type.dart'
    as _i8;
import 'package:parcel_am/features/chat/domain/usecases/chat_usecase.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChatRepositoryImpl_0 extends _i1.SmartFake
    implements _i2.ChatRepositoryImpl {
  _FakeChatRepositoryImpl_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatUseCase extends _i1.Mock implements _i4.ChatUseCase {
  MockChatUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ChatRepositoryImpl get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeChatRepositoryImpl_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ChatRepositoryImpl);

  @override
  _i5.Stream<_i3.Either<_i6.Failure, List<_i7.Message>>> getMessagesStream(
    String? chatId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesStream, [chatId]),
            returnValue:
                _i5.Stream<_i3.Either<_i6.Failure, List<_i7.Message>>>.empty(),
          )
          as _i5.Stream<_i3.Either<_i6.Failure, List<_i7.Message>>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> sendMessage(_i7.Message? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [message]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#sendMessage, [message]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> updateMessageStatus(
    String? messageId,
    _i7.MessageStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMessageStatus, [messageId, status]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#updateMessageStatus, [messageId, status]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> markMessageAsRead(
    String? chatId,
    String? messageId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markMessageAsRead, [chatId, messageId, userId]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#markMessageAsRead, [
                  chatId,
                  messageId,
                  userId,
                ]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> uploadMedia(
    String? filePath,
    String? chatId,
    _i8.MessageType? type,
    dynamic Function(double)? onProgress,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadMedia, [
              filePath,
              chatId,
              type,
              onProgress,
            ]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
              _FakeEither_1<_i6.Failure, String>(
                this,
                Invocation.method(#uploadMedia, [
                  filePath,
                  chatId,
                  type,
                  onProgress,
                ]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, String>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> setTypingStatus(
    String? chatId,
    String? userId,
    bool? isTyping,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setTypingStatus, [chatId, userId, isTyping]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#setTypingStatus, [chatId, userId, isTyping]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> updateLastSeen(
    String? chatId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastSeen, [chatId, userId]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#updateLastSeen, [chatId, userId]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);

  @override
  _i5.Stream<_i3.Either<_i6.Failure, _i9.Chat>> getChatStream(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#getChatStream, [chatId]),
            returnValue: _i5.Stream<_i3.Either<_i6.Failure, _i9.Chat>>.empty(),
          )
          as _i5.Stream<_i3.Either<_i6.Failure, _i9.Chat>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> deleteMessage(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [messageId]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#deleteMessage, [messageId]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);
}
