// Mocks generated by Mockito 5.4.6 from annotations
// in parcel_am/test/features/notifications/presentation/bloc/notification_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:parcel_am/core/errors/failures.dart' as _i6;
import 'package:parcel_am/features/notifications/domain/entities/notification_entity.dart'
    as _i7;
import 'package:parcel_am/features/notifications/domain/repositories/notification_repository.dart'
    as _i2;
import 'package:parcel_am/features/notifications/domain/usecases/notification_usecase.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNotificationRepository_0 extends _i1.SmartFake
    implements _i2.NotificationRepository {
  _FakeNotificationRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NotificationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationUseCase extends _i1.Mock
    implements _i4.NotificationUseCase {
  MockNotificationUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NotificationRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNotificationRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.NotificationRepository);

  @override
  _i5.Stream<_i3.Either<_i6.Failure, List<_i7.NotificationEntity>>>
  watchNotifications(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchNotifications, [userId]),
            returnValue:
                _i5.Stream<
                  _i3.Either<_i6.Failure, List<_i7.NotificationEntity>>
                >.empty(),
          )
          as _i5.Stream<_i3.Either<_i6.Failure, List<_i7.NotificationEntity>>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> markAsRead(
    String? notificationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [notificationId]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#markAsRead, [notificationId]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> markAllAsRead(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#markAllAsRead, [userId]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#markAllAsRead, [userId]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> deleteNotification(
    String? notificationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNotification, [notificationId]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#deleteNotification, [notificationId]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> clearAll(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, [userId]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#clearAll, [userId]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);
}
