// Mocks generated by Mockito 5.4.6 from annotations
// in parcel_am/test/features/travellink/presentation/bloc/auth_bloc_kyc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:parcel_am/core/errors/failures.dart' as _i7;
import 'package:parcel_am/features/travellink/domain/entities/user_entity.dart'
    as _i8;
import 'package:parcel_am/features/travellink/domain/repositories/auth_repository.dart'
    as _i2;
import 'package:parcel_am/features/travellink/domain/repositories/kyc_repository.dart'
    as _i4;
import 'package:parcel_am/features/travellink/domain/usecases/get_current_user_usecase.dart'
    as _i11;
import 'package:parcel_am/features/travellink/domain/usecases/login_usecase.dart'
    as _i5;
import 'package:parcel_am/features/travellink/domain/usecases/logout_usecase.dart'
    as _i10;
import 'package:parcel_am/features/travellink/domain/usecases/register_usecase.dart'
    as _i9;
import 'package:parcel_am/features/travellink/domain/usecases/watch_kyc_status_usecase.dart'
    as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthRepository_0 extends _i1.SmartFake
    implements _i2.AuthRepository {
  _FakeAuthRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKycRepository_2 extends _i1.SmartFake implements _i4.KycRepository {
  _FakeKycRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i5.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, _i8.UserEntity>> call(
    _i5.LoginParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i6.Future<_i3.Either<_i7.Failure, _i8.UserEntity>>.value(
                  _FakeEither_1<_i7.Failure, _i8.UserEntity>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i6.Future<_i3.Either<_i7.Failure, _i8.UserEntity>>);
}

/// A class which mocks [RegisterUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterUseCase extends _i1.Mock implements _i9.RegisterUseCase {
  MockRegisterUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, _i8.UserEntity>> call(
    _i9.RegisterParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i6.Future<_i3.Either<_i7.Failure, _i8.UserEntity>>.value(
                  _FakeEither_1<_i7.Failure, _i8.UserEntity>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i6.Future<_i3.Either<_i7.Failure, _i8.UserEntity>>);
}

/// A class which mocks [LogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUseCase extends _i1.Mock implements _i10.LogoutUseCase {
  MockLogoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, void>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i6.Future<_i3.Either<_i7.Failure, void>>.value(
              _FakeEither_1<_i7.Failure, void>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i6.Future<_i3.Either<_i7.Failure, void>>);
}

/// A class which mocks [GetCurrentUserUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrentUserUseCase extends _i1.Mock
    implements _i11.GetCurrentUserUseCase {
  MockGetCurrentUserUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, _i8.UserEntity?>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i6.Future<_i3.Either<_i7.Failure, _i8.UserEntity?>>.value(
                  _FakeEither_1<_i7.Failure, _i8.UserEntity?>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i6.Future<_i3.Either<_i7.Failure, _i8.UserEntity?>>);
}

/// A class which mocks [ResetPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetPasswordUseCase extends _i1.Mock
    implements _i5.ResetPasswordUseCase {
  MockResetPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, void>> call(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#call, [email]),
            returnValue: _i6.Future<_i3.Either<_i7.Failure, void>>.value(
              _FakeEither_1<_i7.Failure, void>(
                this,
                Invocation.method(#call, [email]),
              ),
            ),
          )
          as _i6.Future<_i3.Either<_i7.Failure, void>>);
}

/// A class which mocks [WatchKycStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchKycStatusUseCase extends _i1.Mock
    implements _i12.WatchKycStatusUseCase {
  MockWatchKycStatusUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.KycRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeKycRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.KycRepository);

  @override
  _i6.Stream<String> call(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [userId]),
            returnValue: _i6.Stream<String>.empty(),
          )
          as _i6.Stream<String>);
}
