// Mocks generated by Mockito 5.4.6 from annotations
// in parcel_am/test/features/travellink/presentation/bloc/kyc_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:parcel_am/core/errors/failures.dart' as _i6;
import 'package:parcel_am/features/travellink/domain/repositories/kyc_repository.dart'
    as _i2;
import 'package:parcel_am/features/travellink/domain/usecases/get_kyc_status_usecase.dart'
    as _i7;
import 'package:parcel_am/features/travellink/domain/usecases/submit_kyc_usecase.dart'
    as _i4;
import 'package:parcel_am/features/travellink/domain/usecases/watch_kyc_status_usecase.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeKycRepository_0 extends _i1.SmartFake implements _i2.KycRepository {
  _FakeKycRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SubmitKycUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubmitKycUseCase extends _i1.Mock implements _i4.SubmitKycUseCase {
  MockSubmitKycUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.KycRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeKycRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.KycRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(_i4.SubmitKycParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [GetKycStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetKycStatusUseCase extends _i1.Mock
    implements _i7.GetKycStatusUseCase {
  MockGetKycStatusUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.KycRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeKycRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.KycRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> call(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [userId]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
              _FakeEither_1<_i6.Failure, String>(
                this,
                Invocation.method(#call, [userId]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, String>>);
}

/// A class which mocks [WatchKycStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchKycStatusUseCase extends _i1.Mock
    implements _i8.WatchKycStatusUseCase {
  MockWatchKycStatusUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.KycRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeKycRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.KycRepository);

  @override
  _i5.Stream<String> call(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#call, [userId]),
            returnValue: _i5.Stream<String>.empty(),
          )
          as _i5.Stream<String>);
}
