// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU4NC2YD_q8AFh2CxLvONQFtLlOec_qh0',
    appId: '1:905050052127:web:94aa2b783d3ee7a081272a',
    messagingSenderId: '905050052127',
    projectId: 'parcel-am',
    authDomain: 'parcel-am.firebaseapp.com',
    storageBucket: 'parcel-am.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBloRvH8JBUr_eA7Y2Hf_do8NRN4jlDf-0',
    appId: '1:905050052127:android:1b2d2b8aa147d61a81272a',
    messagingSenderId: '905050052127',
    projectId: 'parcel-am',
    storageBucket: 'parcel-am.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7_TEQS0o9jwXeG3dEWbWt9HpWlhPNP2Q',
    appId: '1:905050052127:ios:0eaaff5cef3d4bcc81272a',
    messagingSenderId: '905050052127',
    projectId: 'parcel-am',
    storageBucket: 'parcel-am.firebasestorage.app',
    iosBundleId: 'com.example.parcelAm',
  );
}
