// Mocks generated by Mockito 5.4.6 from annotations
// in parcel_am/test/features/travellink/presentation/bloc/chat/chat_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:parcel_am/core/errors/failures.dart' as _i5;
import 'package:parcel_am/features/travellink/domain/entities/chat/chat_entity.dart'
    as _i6;
import 'package:parcel_am/features/travellink/domain/usecases/chat/chat_usecase.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatUseCase extends _i1.Mock implements _i3.ChatUseCase {
  MockChatUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.Either<_i5.Failure, List<_i6.ChatEntity>>> watchUserChats(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchUserChats, [userId]),
            returnValue:
                _i4.Stream<
                  _i2.Either<_i5.Failure, List<_i6.ChatEntity>>
                >.empty(),
          )
          as _i4.Stream<_i2.Either<_i5.Failure, List<_i6.ChatEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ChatEntity>> createChat(
    List<String>? participantIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createChat, [participantIds]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ChatEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ChatEntity>(
                    this,
                    Invocation.method(#createChat, [participantIds]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ChatEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> markAsRead(
    String? chatId,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [chatId, userId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#markAsRead, [chatId, userId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
