// Mocks generated by Mockito 5.4.6 from annotations
// in parcel_am/test/features/travellink/presentation/bloc/chat/presence_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:parcel_am/features/travellink/domain/entities/chat/presence_entity.dart'
    as _i6;
import 'package:parcel_am/features/travellink/domain/failures/failures.dart'
    as _i5;
import 'package:parcel_am/features/travellink/domain/usecases/chat/presence_usecase.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PresenceUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockPresenceUseCase extends _i1.Mock implements _i3.PresenceUseCase {
  MockPresenceUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.Either<_i5.Failure, _i6.PresenceEntity>> watchUserPresence(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchUserPresence, [userId]),
            returnValue:
                _i4.Stream<_i2.Either<_i5.Failure, _i6.PresenceEntity>>.empty(),
          )
          as _i4.Stream<_i2.Either<_i5.Failure, _i6.PresenceEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updatePresence({
    required String? userId,
    required _i6.OnlineStatus? status,
    String? currentChatId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePresence, [], {
              #userId: userId,
              #status: status,
              #currentChatId: currentChatId,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#updatePresence, [], {
                  #userId: userId,
                  #status: status,
                  #currentChatId: currentChatId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> setTypingStatus({
    required String? userId,
    required String? chatId,
    required bool? isTyping,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setTypingStatus, [], {
              #userId: userId,
              #chatId: chatId,
              #isTyping: isTyping,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#setTypingStatus, [], {
                  #userId: userId,
                  #chatId: chatId,
                  #isTyping: isTyping,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Stream<_i2.Either<_i5.Failure, Map<String, bool>>> watchTypingStatus(
    String? chatId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchTypingStatus, [chatId]),
            returnValue:
                _i4.Stream<_i2.Either<_i5.Failure, Map<String, bool>>>.empty(),
          )
          as _i4.Stream<_i2.Either<_i5.Failure, Map<String, bool>>>);
}
