// Mocks generated by Mockito 5.4.6 from annotations
// in parcel_am/test/core/widgets/app_button_kyc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:bloc/bloc.dart' as _i13;
import 'package:dartz/dartz.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:parcel_am/core/bloc/base/base_state.dart' as _i5;
import 'package:parcel_am/core/errors/failures.dart' as _i10;
import 'package:parcel_am/features/kyc/domain/entities/kyc_status.dart' as _i12;
import 'package:parcel_am/features/parcel_am_core/data/models/user_model.dart'
    as _i11;
import 'package:parcel_am/features/parcel_am_core/domain/usecases/auth_usecase.dart'
    as _i2;
import 'package:parcel_am/features/parcel_am_core/presentation/bloc/auth/auth_cubit.dart'
    as _i4;
import 'package:parcel_am/features/parcel_am_core/presentation/bloc/auth/auth_data.dart'
    as _i6;
import 'package:parcel_am/features/passkey/domain/usecases/passkey_usecase.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthUseCase_0 extends _i1.SmartFake implements _i2.AuthUseCase {
  _FakeAuthUseCase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePasskeyUseCase_1 extends _i1.SmartFake
    implements _i3.PasskeyUseCase {
  _FakePasskeyUseCase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthCubit extends _i1.Mock implements _i4.AuthCubit {
  MockAuthCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthUseCase get authUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#authUseCase),
            returnValue: _FakeAuthUseCase_0(
              this,
              Invocation.getter(#authUseCase),
            ),
          )
          as _i2.AuthUseCase);

  @override
  _i3.PasskeyUseCase get passkeyUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#passkeyUseCase),
            returnValue: _FakePasskeyUseCase_1(
              this,
              Invocation.getter(#passkeyUseCase),
            ),
          )
          as _i3.PasskeyUseCase);

  @override
  _i5.BaseState<_i6.AuthData> get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i7.dummyValue<_i5.BaseState<_i6.AuthData>>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i5.BaseState<_i6.AuthData>);

  @override
  _i8.Stream<_i5.BaseState<_i6.AuthData>> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i8.Stream<_i5.BaseState<_i6.AuthData>>.empty(),
          )
          as _i8.Stream<_i5.BaseState<_i6.AuthData>>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i8.Stream<_i9.Either<_i10.Failure, _i11.UserModel>> watchUserData(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchUserData, [userId]),
            returnValue:
                _i8.Stream<_i9.Either<_i10.Failure, _i11.UserModel>>.empty(),
          )
          as _i8.Stream<_i9.Either<_i10.Failure, _i11.UserModel>>);

  @override
  _i8.Future<void> checkCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#checkCurrentUser, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void updateEmail(String? email) => super.noSuchMethod(
    Invocation.method(#updateEmail, [email]),
    returnValueForMissingStub: null,
  );

  @override
  void updatePassword(String? password) => super.noSuchMethod(
    Invocation.method(#updatePassword, [password]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> login(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> register({
    required String? email,
    required String? password,
    required String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #email: email,
              #password: password,
              #displayName: displayName,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateUserProfile(String? displayName) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [displayName]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateUserProfileWithKyc({
    required String? displayName,
    _i12.KycStatus? kycStatus,
    Map<String, dynamic>? additionalData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfileWithKyc, [], {
              #displayName: displayName,
              #kycStatus: kycStatus,
              #additionalData: additionalData,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> resetPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [email]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void updateKycStatus(String? kycStatus) => super.noSuchMethod(
    Invocation.method(#updateKycStatus, [kycStatus]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> checkPasskeySupport() =>
      (super.noSuchMethod(
            Invocation.method(#checkPasskeySupport, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> signInWithPasskey() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPasskey, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void handleException(Exception? exception, [StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#handleException, [exception, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void emitLoading([String? message, double? progress]) => super.noSuchMethod(
    Invocation.method(#emitLoading, [message, progress]),
    returnValueForMissingStub: null,
  );

  @override
  void emitSuccess(String? message, [Map<String, dynamic>? metadata]) =>
      super.noSuchMethod(
        Invocation.method(#emitSuccess, [message, metadata]),
        returnValueForMissingStub: null,
      );

  @override
  void emitError(
    String? message, {
    Exception? exception,
    StackTrace? stackTrace,
    String? errorCode,
    bool? isRetryable = true,
  }) => super.noSuchMethod(
    Invocation.method(
      #emitError,
      [message],
      {
        #exception: exception,
        #stackTrace: stackTrace,
        #errorCode: errorCode,
        #isRetryable: isRetryable,
      },
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> executeAsync<T>(
    _i8.Future<T> Function()? operation, {
    void Function(T)? onSuccess,
    void Function(Exception)? onError,
    String? loadingMessage,
    String? successMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #executeAsync,
              [operation],
              {
                #onSuccess: onSuccess,
                #onError: onError,
                #loadingMessage: loadingMessage,
                #successMessage: successMessage,
              },
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void onChange(_i13.Change<_i5.BaseState<_i6.AuthData>>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i5.BaseState<_i6.AuthData>? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}
