// Mocks generated by Mockito 5.4.6 from annotations
// in parcel_am/test/core/widgets/app_button_kyc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:bloc/bloc.dart' as _i11;
import 'package:dartz/dartz.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:parcel_am/core/bloc/base/base_state.dart' as _i4;
import 'package:parcel_am/core/errors/failures.dart' as _i9;
import 'package:parcel_am/features/parcel_am_core/data/models/user_model.dart'
    as _i10;
import 'package:parcel_am/features/parcel_am_core/domain/usecases/auth_usecase.dart'
    as _i2;
import 'package:parcel_am/features/parcel_am_core/presentation/bloc/auth/auth_bloc.dart'
    as _i3;
import 'package:parcel_am/features/parcel_am_core/presentation/bloc/auth/auth_data.dart'
    as _i5;
import 'package:parcel_am/features/parcel_am_core/presentation/bloc/auth/auth_event.dart'
    as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthUseCase_0 extends _i1.SmartFake implements _i2.AuthUseCase {
  _FakeAuthUseCase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthBloc extends _i1.Mock implements _i3.AuthBloc {
  MockAuthBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthUseCase get authUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#authUseCase),
            returnValue: _FakeAuthUseCase_0(
              this,
              Invocation.getter(#authUseCase),
            ),
          )
          as _i2.AuthUseCase);

  @override
  _i4.BaseState<_i5.AuthData> get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i6.dummyValue<_i4.BaseState<_i5.AuthData>>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i4.BaseState<_i5.AuthData>);

  @override
  _i7.Stream<_i4.BaseState<_i5.AuthData>> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i4.BaseState<_i5.AuthData>>.empty(),
          )
          as _i7.Stream<_i4.BaseState<_i5.AuthData>>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i7.Stream<_i8.Either<_i9.Failure, _i10.UserModel>> watchUserData(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchUserData, [userId]),
            returnValue:
                _i7.Stream<_i8.Either<_i9.Failure, _i10.UserModel>>.empty(),
          )
          as _i7.Stream<_i8.Either<_i9.Failure, _i10.UserModel>>);

  @override
  void handleException(Exception? exception, [StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#handleException, [exception, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void emitLoading([String? message, double? progress]) => super.noSuchMethod(
    Invocation.method(#emitLoading, [message, progress]),
    returnValueForMissingStub: null,
  );

  @override
  void emitSuccess(String? message, [Map<String, dynamic>? metadata]) =>
      super.noSuchMethod(
        Invocation.method(#emitSuccess, [message, metadata]),
        returnValueForMissingStub: null,
      );

  @override
  void emitError(
    String? message, {
    Exception? exception,
    StackTrace? stackTrace,
    String? errorCode,
    bool? isRetryable = true,
  }) => super.noSuchMethod(
    Invocation.method(
      #emitError,
      [message],
      {
        #exception: exception,
        #stackTrace: stackTrace,
        #errorCode: errorCode,
        #isRetryable: isRetryable,
      },
    ),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i11.Transition<_i12.AuthEvent, _i4.BaseState<_i5.AuthData>>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void add(_i12.AuthEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i12.AuthEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i4.BaseState<_i5.AuthData>? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i12.AuthEvent>(
    _i11.EventHandler<E, _i4.BaseState<_i5.AuthData>>? handler, {
    _i11.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onChange(_i11.Change<_i4.BaseState<_i5.AuthData>>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
