// Mocks generated by Mockito 5.4.6 from annotations
// in parcel_am/test/features/parcel_am_core/presentation/widgets/delivery_card_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:parcel_am/core/services/navigation_service/nav_config.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i2.NavigationService {
  MockNavigationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<T?> navigateTo<T>(String? routeName, {Object? arguments}) =>
      (super.noSuchMethod(
            Invocation.method(
              #navigateTo,
              [routeName],
              {#arguments: arguments},
            ),
            returnValue: _i3.Future<T?>.value(),
          )
          as _i3.Future<T?>);

  @override
  _i3.Future<void> navigateAndReplace(String? routeName, {Object? arguments}) =>
      (super.noSuchMethod(
            Invocation.method(
              #navigateAndReplace,
              [routeName],
              {#arguments: arguments},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> navigateAndReplaceAll(
    String? routeName, {
    Object? arguments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #navigateAndReplaceAll,
              [routeName],
              {#arguments: arguments},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> navigateAndOffAll(
    String? destinationRoute,
    dynamic conditionRoute, {
    Object? arguments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #navigateAndOffAll,
              [destinationRoute, conditionRoute],
              {#arguments: arguments},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void goBack<T>({T? result}) => super.noSuchMethod(
    Invocation.method(#goBack, [], {#result: result}),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> goBackUntil(String? routeName) =>
      (super.noSuchMethod(
            Invocation.method(#goBackUntil, [routeName]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
