// Mocks generated by Mockito 5.4.6 from annotations
// in parcel_am/test/features/parcel_am_core/presentation/widgets/status_update_action_sheet_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:bloc/bloc.dart' as _i10;
import 'package:dartz/dartz.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:parcel_am/core/bloc/base/base_state.dart' as _i3;
import 'package:parcel_am/core/errors/failures.dart' as _i9;
import 'package:parcel_am/features/parcel_am_core/domain/entities/parcel_entity.dart'
    as _i7;
import 'package:parcel_am/features/parcel_am_core/presentation/bloc/parcel/parcel_cubit.dart'
    as _i2;
import 'package:parcel_am/features/parcel_am_core/presentation/bloc/parcel/parcel_state.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ParcelCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockParcelCubit extends _i1.Mock implements _i2.ParcelCubit {
  MockParcelCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.BaseState<_i4.ParcelData> get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i5.dummyValue<_i3.BaseState<_i4.ParcelData>>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.BaseState<_i4.ParcelData>);

  @override
  _i6.Stream<_i3.BaseState<_i4.ParcelData>> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i3.BaseState<_i4.ParcelData>>.empty(),
          )
          as _i6.Stream<_i3.BaseState<_i4.ParcelData>>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i6.Future<void> createParcel(_i7.ParcelEntity? parcel) =>
      (super.noSuchMethod(
            Invocation.method(#createParcel, [parcel]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateParcelStatus(
    String? parcelId,
    _i7.ParcelStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateParcelStatus, [parcelId, status]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> loadParcel(String? parcelId) =>
      (super.noSuchMethod(
            Invocation.method(#loadParcel, [parcelId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> loadUserParcels(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#loadUserParcels, [userId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> assignTraveler(String? parcelId, String? travelerId) =>
      (super.noSuchMethod(
            Invocation.method(#assignTraveler, [parcelId, travelerId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> confirmDelivery(String? parcelId, String? escrowId) =>
      (super.noSuchMethod(
            Invocation.method(#confirmDelivery, [parcelId, escrowId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cancelParcel({
    required String? parcelId,
    required String? userId,
    required double? amount,
    String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#cancelParcel, [], {
              #parcelId: parcelId,
              #userId: userId,
              #amount: amount,
              #reason: reason,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Stream<_i8.Either<_i9.Failure, _i7.ParcelEntity>> watchParcelStatus(
    String? parcelId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchParcelStatus, [parcelId]),
            returnValue:
                _i6.Stream<_i8.Either<_i9.Failure, _i7.ParcelEntity>>.empty(),
          )
          as _i6.Stream<_i8.Either<_i9.Failure, _i7.ParcelEntity>>);

  @override
  _i6.Stream<_i8.Either<_i9.Failure, List<_i7.ParcelEntity>>> watchUserParcels(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchUserParcels, [userId]),
            returnValue:
                _i6.Stream<
                  _i8.Either<_i9.Failure, List<_i7.ParcelEntity>>
                >.empty(),
          )
          as _i6.Stream<_i8.Either<_i9.Failure, List<_i7.ParcelEntity>>>);

  @override
  _i6.Stream<_i8.Either<_i9.Failure, List<_i7.ParcelEntity>>>
  watchAcceptedParcels(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchAcceptedParcels, [userId]),
            returnValue:
                _i6.Stream<
                  _i8.Either<_i9.Failure, List<_i7.ParcelEntity>>
                >.empty(),
          )
          as _i6.Stream<_i8.Either<_i9.Failure, List<_i7.ParcelEntity>>>);

  @override
  _i6.Stream<_i8.Either<_i9.Failure, List<_i7.ParcelEntity>>>
  watchAvailableParcels() =>
      (super.noSuchMethod(
            Invocation.method(#watchAvailableParcels, []),
            returnValue:
                _i6.Stream<
                  _i8.Either<_i9.Failure, List<_i7.ParcelEntity>>
                >.empty(),
          )
          as _i6.Stream<_i8.Either<_i9.Failure, List<_i7.ParcelEntity>>>);

  @override
  void handleException(Exception? exception, [StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#handleException, [exception, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void emitLoading([String? message, double? progress]) => super.noSuchMethod(
    Invocation.method(#emitLoading, [message, progress]),
    returnValueForMissingStub: null,
  );

  @override
  void emitSuccess(String? message, [Map<String, dynamic>? metadata]) =>
      super.noSuchMethod(
        Invocation.method(#emitSuccess, [message, metadata]),
        returnValueForMissingStub: null,
      );

  @override
  void emitError(
    String? message, {
    Exception? exception,
    StackTrace? stackTrace,
    String? errorCode,
    bool? isRetryable = true,
  }) => super.noSuchMethod(
    Invocation.method(
      #emitError,
      [message],
      {
        #exception: exception,
        #stackTrace: stackTrace,
        #errorCode: errorCode,
        #isRetryable: isRetryable,
      },
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> executeAsync<T>(
    _i6.Future<T> Function()? operation, {
    void Function(T)? onSuccess,
    void Function(Exception)? onError,
    String? loadingMessage,
    String? successMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #executeAsync,
              [operation],
              {
                #onSuccess: onSuccess,
                #onError: onError,
                #loadingMessage: loadingMessage,
                #successMessage: successMessage,
              },
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void onChange(_i10.Change<_i3.BaseState<_i4.ParcelData>>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.BaseState<_i4.ParcelData>? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
