// Mocks generated by Mockito 5.4.6 from annotations
// in parcel_am/test/features/parcel_am_core/presentation/widgets/status_update_action_sheet_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_bloc/flutter_bloc.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:parcel_am/core/bloc/base/base_state.dart' as _i3;
import 'package:parcel_am/features/parcel_am_core/presentation/bloc/parcel/parcel_bloc.dart'
    as _i2;
import 'package:parcel_am/features/parcel_am_core/presentation/bloc/parcel/parcel_event.dart'
    as _i8;
import 'package:parcel_am/features/parcel_am_core/presentation/bloc/parcel/parcel_state.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ParcelBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockParcelBloc extends _i1.Mock implements _i2.ParcelBloc {
  MockParcelBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.BaseState<_i4.ParcelData> get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i5.dummyValue<_i3.BaseState<_i4.ParcelData>>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.BaseState<_i4.ParcelData>);

  @override
  _i6.Stream<_i3.BaseState<_i4.ParcelData>> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i3.BaseState<_i4.ParcelData>>.empty(),
          )
          as _i6.Stream<_i3.BaseState<_i4.ParcelData>>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void handleException(Exception? exception, [StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#handleException, [exception, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void emitLoading([String? message, double? progress]) => super.noSuchMethod(
    Invocation.method(#emitLoading, [message, progress]),
    returnValueForMissingStub: null,
  );

  @override
  void emitSuccess(String? message, [Map<String, dynamic>? metadata]) =>
      super.noSuchMethod(
        Invocation.method(#emitSuccess, [message, metadata]),
        returnValueForMissingStub: null,
      );

  @override
  void emitError(
    String? message, {
    Exception? exception,
    StackTrace? stackTrace,
    String? errorCode,
    bool? isRetryable = true,
  }) => super.noSuchMethod(
    Invocation.method(
      #emitError,
      [message],
      {
        #exception: exception,
        #stackTrace: stackTrace,
        #errorCode: errorCode,
        #isRetryable: isRetryable,
      },
    ),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i7.Transition<_i8.ParcelEvent, _i3.BaseState<_i4.ParcelData>>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void add(_i8.ParcelEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i8.ParcelEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.BaseState<_i4.ParcelData>? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i8.ParcelEvent>(
    _i7.EventHandler<E, _i3.BaseState<_i4.ParcelData>>? handler, {
    _i7.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i7.Change<_i3.BaseState<_i4.ParcelData>>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
